### ISSUE TITLE
Ошибка в "3.1. Создание моделей в пространстве имен"

### ISSUE THREAD

**Issue by audiosupp** [rusrails/rusrails#534]
https://rusrails.ru/active-record-basics#overriding-the-naming-conventions

> Например, файлы order.rb и **order.rb** можно разместить в app/models/books с именами классов Book::Order и Book::Review соответственно.

Как в оригинале:

> For example, order.rb and **review.rb** under app/models/book with Book::Order and Book::Review class names, respectively.

https://guides.rubyonrails.org/active_record_basics.html

**Comment by mikdiet** [comment]
fixed, ty
